#!/usr/bin/env python
# -*- coding: utf-8 -*-
#感受：（1）了解二维数组的使用（2）注意每个变量放置的位置，如果没有放在正确的循环里，会导致奇怪的结果
#      （3）在编写程序之前要清晰的知道自己的目的，如，此程序的最终目的是要找到domain后将序列的名字更改成目的名字，终极目的是改名字，所以可以设置name空字符串，在找到后就更改名字，最终完成循环后，将序列加在名字后即可
import sys
import re

fasta_file = sys.argv[1]
#列出序列中所有可能的domain
HA=["AGACP.W","ASACP.W","ASSCP.W","NSCCP.F","SCCCP.W","SMCCP.W","SSACP.W","SSCCP.F","SSCCP.W","SSCCP.Y","SSCSP.W","SSSCP.W","TASCP.W","TGVCP.F","TSACP.W","TSCCF.W","TSCCN.W","TSCCP.F","TSCCP.W","TSCCP.Y","TSCCS.W","TSCCS.Y","TSCSP.W","TSSCP.W","TSTCT.W","VSACP.W"]
HB=["APC..K..E","GPC..K..E","IPC..K..E","MPC..K..E","QPC..R..E","TPC..K..E","VPC..K..E","YPC..K..E"]
HC=["MAC..GC..GAG","MAC..GC..GGA","MAC..GC..GGG","MAC..GC..GPA","MAC..GC..GPG","MAC..GC..GPK","MAC..GC..GPS","MAC..GC..GPW","MAC..GC..GVG","MCC..GC..GGG","MGC..GC..GAG","MGC..GC..GGG","MGC..GC..GMG","MGC..GC..GPH","MGC..GC..GPK","MMC..GC..GAG","MMC..GC..GPA","MNC..GC..GGG","MSC..GC..GAA","MSC..GC..GAG","MSC..GC..GGG","MSC..GC..GPG","MSC..GC..GPS","MTC..GC..GGG","MTC..GC..GPS"]
FA=["DAAKCIKCMRCIQVC","DTDACIFCGQCVQIC","DAHRCVVCGQCVQTC","DASKCIVCGRCVEVC","DASKCKGCDACKKFC","DATKCEACGECEAVC","DDQKCILCGQCIEVC","DDQKCILCGQCLDVC","DDRKCILCGQCTEAC","DDRKCVLCGQCIEVC","DEDLCVECRLCAGIC","DEKLCINCGKCMENC","DERRCVNCGQCVVTC","DESKCIKCMRCIQIC","DESKCKGCDTCKSFC","DFSLCIKCMRCVQVC","DKEKCVRCGRCREAC","DLDKCIMCRRCENMC","DMAKCVKCGRCVEMC","DMDKCVLCKRCVRTC","DMDKCVLCRRCVRTC","DMNKCIDCGRCVRAC","DMNKCILCRRCIRAC","DMNKCIYCRRCEMMC","DMNKCVLCRRCVRAC","DMNKCVLCRRCVRTC","DNDKCIKCMRCIKVC","DNDKCILCRRCETMC","DNNKCILCRRCVAAC","DNNKCISCGRCVAAC","DNSKCIGCYRCIQVC","DNSKCILCGDCVRAC","DNTKCILCGDCVRVC","DNTKCINCHLCIRAC","DPAKCILCGNCVRMC","DPDKCIRCTRCIRTC","DPEKCQGCGECDNHC","DPEKCRECGRCMKAC","DPKICKGCDSCKSFC","DPKKCVNCGICKNAC","DPNKCIACGRCVRVC","DPNKCILCGACVRAC","DPNKCILCGRCVRTC","DPNKCILCQRCKTIC","DPSKCILCGDCVRMC","DQDKCIKCGKCYNQC","DQDKCIKCGRCVTVC","DQDKCIKCMKCVQVC","DQDLCIKCGRCHDVC","DQEKCIKCGKCKSVC","DQEKCIKCGRCMDAC","DQEKCILCGRCIRVC","DQTRCVECGLCARNC","DSKKCIKCMRCIQVC","DSSKCIGCGMCKNTC","DSSKCIKCMRCVAIC","DSSKCVLCGRCIAAC","DSTRCIKCMRCIQVC","DTARCVICGQCVQMC","DTSKCIKCYKCVKVC","DTSRCILCGDCVRMC","DTTSCINCKKCTKVC","DVNKCVRCMRCVEVC","DYDKCIQCMRCIQVC","DYSKCIKCRRCEAVC","DYSRCVKCMRCIQIC","EESKCKNCTLCRRVC","FEEKCIKCGMCRDIC","HEERCIKCGQCKQVC","IENRCVKCMRCIQVC","IESLCIKCGQCRDVC","IMDNCIGCDKCTKVC","ITEKCIGCTACARVC","ITKKCIGCSNCKRAC","ITSKCIGCGACKRAC","LEDKCTNCGLCKKVC","LEFKCIKCGNCKTVC","NASKCIKCMRCVQIC","NEDLCEACDTCRKVC","NEGNCVGCHTCSSVC","NESLCVNCSMCRQVC","NHDTCVSCGICHKSC","NKDKCVRCGRCVEAC","NKENCVGCDTCRKFC","NMEKCILCRRCETVC","NNDKCINCLRCIQIC","NNDKCIRCMRCIQVC","NPEKCIKCGRCVVVC","NPNKCILCGDCVRVC","NPNKCVMCRRCETMC","NQDKCVGCDTCKGHC","NQDLCADCGHCLAVC","NQQKCIECGRCHQVC","NREICVNCGQCVQIC","NSAKCIKCMRCVQVC","NSKKCVKCMRCIQVC","NSQSCVGCDTCRHVC","NYEKCIKCMRCIQVC","SFEKCIKCMRCIQVC"]
FAB=["SLKDCLACSGCITSA","SLNDCLACSGCITSA","SLTDCLACSGCVTSA","TLADCLACSGCITSA","TLKDCLACSGCITSA","TLNDCLACSGCITSA","TLQDCLACSGCVTTA","VEEKCIRCGMCKQVC","VTSDCHGCDHCTSVC","WEEKCIRCGMCKEAC"]
FB=["CALCGQCITHCP","CANCGQCILVCP","CANCGQCVTVCP","CIACGQCLINCP","CIACGQCVLACP","CIECGQCIVHCP","CIFCGNCMRECP","CIFCGRCTRSCP","CIHCGQCAAVCP","CIHCGQCANVCP","CIHCGQCINVCP","CIHCGQCIPVCP","CIHCGQCTLWCP","CIKCGQCSAHCP","CINCGQCALWCP","CINCGQCANVCP","CINCGQCILNCP","CINCGQCINHCP","CINCGQCINRCP","CINCGQCLLNCP","CINCGQCLNRCP","CINCGQCLTHCP","CINCGQCLVNCP","CINCGQCSAVCP","CIRCGHCLTVCP","CISCGKCLKSCP","CISCGQCAAVCP","CISCGQCIKVCT","CISCGQCSQICP","CIYCGKCIGACP","CIYCGKCLKACP","CIYCGKCLNACP","CIYCGQCANVCP","CLNCGQCLISCP","CLQCGQCLVNCP","CLSCGQCLISCP","CLSCGQCMINCP","CNDCGECVNVCQ","CSLCGQCITHCP","CSTCGDCISACK","CTDCGFCVEGCP","CTFCGQCITHCP","CTFCGQCVAVCP","CTFCGQCVSVCP","CTHCGACISACP","CTHCGACLSTCP","CTHCGQCIAACP","CTHCGQCVSACP","CTLCGQCITHCP","CTLCGQCVVNCP","CTSCGKCIVSCP","CTSCGNCVYQCP","CTYCGQCADVCP","CVACGQCITHCP","CVDCGQCASHCP","CVGCGQCIQTCP","CVGCSECVNNCH","CVHCGQCANACP","CVHCGQCASACP","CVLCGQCVAYCP","CVNCGQCAAVCP","CVNCGQCALWCP","CVNCGQCIVVCP","CVNCGQCTAYCP","CVNCGQCTHWCP","CVNCGQCVAVCP","CVRCGQCIMVCP","CVSCGHCAVSCP","CVSCGLCTVSCP","CVSCGMCLVNCP","CVSCGMCMVSCP","CVSCGQCIVACP","CVSCGQCLVNCP","CVSCGQCMVSCP","CVSCGQCVRACP","CVYCGQCISVCP","CVYCGQCLIACP","CVYCGQCVAYCP","CVYCGQCVSVCP"]
FC=["CAFKPLCHTPGTCAVCIVRVKRADGQELTLTSC","CAHPDLRAAGVCRVCMVEVKGQRTLQPAC","CDHPDLRPIGVCRICVVEIEGQRDLQTAC","CFLEGVNEIGACRVCVVEVEGHERLFTAC","CFLKDINEIGACRVCVVEIEGVDKLASAC","CFLKDLNEIGACRICIVELEGTNKLITSC","CFLKELNEIGACRICCVEIEGKEALVASC","CFLKGINEIAACRVCVVELEGKDKLITSC","CHDIRLKRSNGSCGLCVVEVGTEAPRDVKAC","CHHDDLCTAGVCRICVVAVEGMRTLQAAC","CHHDDLCTAGVCRICVVEVEGARTLQASC","CHHEDLCVAGVCRVCVVEVEGMRTLQASC","CHMKLDNFNYENKPSSCRICMVEVEGRPKLCTAC","CKHPDVDPSAGCGMCIVRVNGRVMRSC","CQMKIDEIGFTNECASCRVCMVSAGRKLVPAC","CYDIRLERSNGNCGLCVVTLISPDGERDVKAC","CYFEGLKSYSGCRVCVVEIEGEPRLATSC","CYHEDLCISGVCRVCVVEVEGMRTLQASC","CYHPDIPPTSACGICVVKLANQGNKYTRAC","CYHPDLKVRATCRICVVEVKGQRKLKTAC","CYHPDLRPEGACRLCMVEASGARTLVASC","CYHPDLSLFGSCRVCVVENAKTGDLLASC","CYLKDINEIGACRICMVEVEGYARLVPSC","CYLKDINEIGACRVCVVEIKGIERLVTSC","CYLKDINQIGACRICLVEVSENQRPYRMVASC","CYLKDLNCIGSCRVCLVDVEGQGLVAAC","CYLKDLNEIAACRVCVVEVDGKDKLITSC","CYLKDLNEIAACRVCVVEVEGKGKLITAC","CYLKDLNEIGACRVCIVEIEGIDQLVASC","CYLKDVNEIGACRVCVVEVEGIDQLVASC","CYLKEINEIGACRVCVVEVEGITKLVTAC","CYLKGINEIAACRVCVVELEGKEKLITSC","CYLKGINEIAACRVCVVELEGKERLITSC","CYLNLHELGCKNDPGVCRICVVEVEGRKNLAPAC","CYLRDLNEIGGCRVCVVEVEGCDQLVAAC","CYLRDLNTAGSCRVCVVEIEGTRTLQAAC","CYLRELNEIGSCRVCVVEVKGRERLVASC","CYLSETSIYGACRLCLVEVDGKSIVTSC","CYLSETSIYGACRMCLVEVDGKDIVTSC","CYLSETSVYGACRMCLVEVDGQLVTSC","CYMKELNEIGACRVCVVEVEGYERLFTAC","CYMNIPEIGFKNDCASCRICVVEVVGRKNLVPAC","CYMNLKDMCITNLPASCRICVVEVEGRRNLAPAC","CYQPELSIYGACRMCLVDIEGRGILSSC","CYRPDLTPFGACRMCVVEVEGRGIQSSC","CYWEGLNEIGACRVCVVEVEGNKRLPAAC","CYWKGLNEIGACRVCVVEVEGYERLFTAC","CYYSDLSIYGACRMCVVEDQWGGIIASC","CYYSELSTYGACRMCVVEDARGKIDSSC","CYYTDMSIYGACRMCVVEDERGSVIASC"]
FD=["HCGDCNTCHRNHNC","HCRDCTTCEKNGKC","HCRDCTVCEKNGNC","HDATCTTCVRSGNC","HDCFCATCVRSGNC","HDCKCATCVRSGNC","HDCNCPSCVRSGNC","HDCQCVTCARSGCC","HDDHCPSCVRSGNC","HDFKCATCVRSGNC","HDFRCAACQRNGSC","HDGDCTTCEMNGKC","HDKECLTCEKSGNC","HDMDCVTCGRYGNC","HDNRCVVCPRNGNC","HDSECTSCVRSGNC","HDSRCTSCVRSGNC","HECDCTVCSKSGSC","HEKHCLSCVRSTTC","HETKCTKCTRSGNC","HNADCVAPCVETCP","HNADCVAPCVMTCP","HNANCTMCTRSGNC","HNCFCPTCVRSGNC","HNLDCPSCSANGMC","HNRDCTTCERNGSC","HNRDCTVCERNGSC","HNRECPTCVRSASC","HNSSCTSCVRSRNC","HNTNCAVCVRSGNC","HPKDCLCCQKNGDC","HPKDCLVCPKNLNC","HPNDCLICPKSGNC","HPNDCLNCIRNGEC","HPNDCMTCDVNGRC","HPNECLTCERSGTC","HPNECLTCIRSGHC","HPNECLTCSKNGYC","HPNSCLTCAKSMNC","HPQDCFNCERNQNC","HPQDCLKCGKSTVC","HPQDCLKCVRNTSC","HPQDCYTCAKSGKC","HPTDCLICAKNGKC","HRALCATCVRQDTC","HRFDCWKCPREHNC","HSNKCVSCARNQNC","HYCHCTTCVRSGNC","HYGDCNTCKRNNNC","HYGDCTVCKRNNNC","HYGECYSCFRNNNC","HYGECYSCVRNNNC"]

#构建二维数组
domain=[HA,HB,HC,FA,FAB,FB,FC,FD]

#打开fasta文件
file_object = open(fasta_file)
try:
        all_the_fasta = file_object.read( )
finally:
        file_object.close()

#使用“>”将fasta文件分成单个序列
fastas = all_the_fasta.split('>')

#遍历各个序列
for fasta in fastas:
#    print fasta
#在循环遍历domain之前设置i变量，针对每个fasta序列都使i=0
    i = 0
    # found=0   #如果想只输出找到目的domain的序列，则在此设置一个值found,初始为0，如果找到则为1，如果为1，则输出，否则，continue
#设置空字符串name，针对每个fasta序列都使name为空
    name=""
#遍历二维数组domain
    for dom in domain:
#每循环一个dom，则i加1
        i = i + 1
#遍历dom中的各个元素
        for element in dom:
#在fasta文件中寻找元素
            f = re.findall(element,fasta)
            if len(f) > 0:
                # found=1
#如果找到，则使名字的字符串加上所找到的元素所在的dom的名字
                name = name +'domain'  + str(i) + '_'
# if found== 1:
#当针对一个fasta序列的循环结束后，将已经把名字改掉的序列输出
    print '>' + name + fasta
